name: json-lesson
version: 0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- aeson

library:
  source-dirs: src

executables:
  ch40-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-lesson
    default-extensions:
    - OverloadedStrings
    - DeriveGeneric

tests:
  ch40-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-lesson
