name: gpwh
dependencies:
  - base
  - containers

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src

executables:
  lesson01-01:
    main: app/Lesson01/hello.hs
  lesson01-email:
    main: app/Lesson01/FirstProg.hs
    dependencies:
      - gpwh