name: db-lesson
version: 0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- sqlite-simple
- time

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  db-lesson-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-lesson

tests:
  db-lesson-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-lesson
